version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: ''
       MYSQL_DATABASE: ''

    ports:
      - "3307:3306"
    networks:
      - chat_network

  chat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5670:80"
    depends_on:
      - mysql
    networks:
      - chat_network

networks:
  chat_network:
    driver: bridge
